AssignmentV3/Controllers/ReservationsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using AssignmentV3.Models;
using AssignmentV3.Utils;
using Microsoft.AspNet.Identity;

namespace AssignmentV3.Controllers
{
    [Authorize]
    public class ReservationsController : Controller
    {
        private BusinessDBContainer db = new BusinessDBContainer();

        // GET: Reservations
        public ActionResult Index()
        {
            var userId = User.Identity.GetUserId();
            var reservations = db.Reservations.Where(r => r.UserId == userId).ToList();
            return View(reservations);
        }
        
        // GET: Reservations/Create
        public ActionResult Create()
        {
            ViewBag.ProgramId = new SelectList(db.Programs, "ProgramId", "ProgramName");
            return View();
        }

        // POST: Reservations/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateInput(false)]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,ProgramId,DatetimeStart,DatetimeEnd,Comment")] Reservation reservation)
        {
            reservation.memberEmail = User.Identity.GetUserName();
            reservation.UserId = User.Identity.GetUserId();            
            reservation.Status = "Approved";
            if (ModelState.IsValid)
            {
                
                db.Reservations.Add(reservation);
                db.SaveChanges();

                try
                {
                    String toEmail = reservation.memberEmail;
                    String subject = "Fitness Center - Confirmation of booking";
                    String contents = "This is the confirmatin of your booking";
                    Program tempProgram = db.Programs.Find(reservation.ProgramId);
                    String program = tempProgram.ProgramName.ToString();
                    //String program = reservation.ProgramId.ToString();
                    String starttime = reservation.DatetimeStart.ToString();
                    String endtiem = reservation.DatetimeEnd.ToString();

                    EmailSender es = new EmailSender();
                    es.ReservationSendMail(toEmail, subject, contents, program, starttime, endtiem);

                    ViewBag.Result = "Email has been send.";

                    ModelState.Clear();
                }
                catch
                {
                    return View();
                }

                return RedirectToAction("Index");
            }

            ViewBag.ProgramId = new SelectList(db.Programs, "ProgramId", "ProgramName", reservation.ProgramId);
            return View(reservation);
        }

        // GET: Reservations/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Reservation reservation = db.Reservations.Find(id);
            if (reservation == null)
            {
                return HttpNotFound();
            }
            ViewBag.ProgramId = new SelectList(db.Programs, "ProgramId", "ProgramName", reservation.ProgramId);
            return View(reservation);
        }

        // POST: Reservations/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateInput(false)]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,ProgramId,DatetimeStart,DatetimeEnd,Comment")] Reservation reservation)
        {
            reservation.memberEmail = User.Identity.GetUserName();
            reservation.UserId = User.Identity.GetUserId();
            reservation.Status = "Approved";
            if (ModelState.IsValid)
            {
                db.Entry(reservation).State = EntityState.Modified;
                db.SaveChanges();

                try
                {
                    String toEmail = reservation.memberEmail;
                    String subject = "Fitness Center - Confirmation of booking";
                    String contents = "This is the confirmatin of your booking";
                    Program tempProgram = db.Programs.Find(reservation.ProgramId);
                    String program = tempProgram.ProgramName.ToString();
                    //String program = reservation.ProgramId.ToString();
                    String starttime = reservation.DatetimeStart.ToString();
                    String endtiem = reservation.DatetimeEnd.ToString();

                    EmailSender es = new EmailSender();
                    es.ReservationSendMail(toEmail, subject, contents, program, starttime, endtiem);

                    ViewBag.Result = "Email has been send.";

                    ModelState.Clear();
                }
                catch
                {
                    return View();
                }

                return RedirectToAction("Index");
            }
            ViewBag.ProgramId = new SelectList(db.Programs, "ProgramId", "ProgramName", reservation.ProgramId);
            return View(reservation);
        }

        // GET: Reservations/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Reservation reservation = db.Reservations.Find(id);
            if (reservation == null)
            {
                return HttpNotFound();
            }
            return View(reservation);
        }

        // POST: Reservations/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Reservation reservation = db.Reservations.Find(id);
            db.Reservations.Remove(reservation);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        protected override void HandleUnknownAction(string actionName)
        {
            Response.Redirect("~/Home/Index");
            base.HandleUnknownAction(actionName);
        }
    }
}

AssignmentV3/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>XIIFIT</title>
    <meta name="description" content="">
    <meta name="author" content="">

    <title>@ViewBag.Title</title>
    <link rel="shortcut icon" href="~/img/icon/icon-2.png" type="image/x-icon">
    <link rel="apple-touch-icon" href="~/img/apple-touch-icon.png">
    <link rel="apple-touch-icon" sizes="72x72" href="~/img/apple-touch-icon-72x72.png">
    <link rel="apple-touch-icon" sizes="114x114" href="~/img/apple-touch-icon-114x114.png">

    <!-- Bootstrap -->
    <link href="~/Content/bootstrap.css" rel="stylesheet" />
    <link href="~/Content/font-awesome.css" rel="stylesheet" />

    <!-- Stylesheet
        ================================================== -->
    <link href="~/Content/style.css" rel="stylesheet" />
    <link href="~/Content/nivo-lightbox.css" type="text/css" rel="stylesheet" />
    <link href="~/Content/default.css" type="text/css" rel="stylesheet" />
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet">
</head>

<body id="page-top" data-spy="scroll" data-target=".navbar-fixed-top">
    <nav id="menu" class="navbar navbar-default navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand page-scroll" href="/Home/Index#header">XIIFIT</a>
            </div>
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav navbar-right">
                    <li><a href="/Home/Index#about" class="page-scroll">About</a></li>
                    <li><a href="/Home/Index#services" class="page-scroll">programs</a></li>
                    <li><a href="/Home/Index#portfolio" class="page-scroll">Facilities</a></li>
                    <li><a href="/Home/Index#testimonials" class="page-scroll">Success Stories</a></li>
                    <li><a href="/Home/Index#contact" class="page-scroll">Contact</a></li>
                    @if (User.Identity.IsAuthenticated)
                    {
                        <li>@Html.ActionLink("Need Help?", "Index", "Reservations")</li>
                    }
                    @Html.Partial("_LoginPartial")
                </ul>               
            </div>
        </div>
    </nav>
    @RenderBody()
    <div id="footer">
        <div class="container text-center">
            <p>&copy; @DateTime.Now.Year  <a href="/Home/Index" rel="nofollow">XIIFIT</a></p>
        </div>
    </div>
    <script type="text/javascript" src="~/Scripts/jquery-3.3.1.js"></script>
    <script type="text/javascript" src="~/Scripts/bootstrap.js"></script>
    <script type="text/javascript" src="~/Scripts/SmoothScroll.js"></script>
    <script type="text/javascript" src="~/Scripts/nivo-lightbox.js"></script>
    <script type="text/javascript" src="~/Scripts/jqBootstrapValidation.js"></script>
    <script type="text/javascript" src="~/Scripts/contact_me.js"></script>
    <script type="text/javascript" src="~/Scripts/main.js"></script>
    
        @Scripts.Render("~/bundles/jquery")
        @Scripts.Render("~/bundles/bootstrap")
        @RenderSection("scripts", required: false)
    
</body>
</html>